/* eslint-disable @next/next/no-page-custom-font */
import { Geist, Geist_Mono, Readex_Pro } from "next/font/google"
import "../globals.css"
import { Providers } from "../providers"
import { SidebarProvider } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/dashboard/appSidebar"
import { SidebarTrigger } from "@/components/ui/sidebar"

// Fonts
const readexPro = Readex_Pro({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-readex-pro",
})

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
})

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${readexPro.variable} antialiased`}
      >
        <Providers>
          <SidebarProvider>
            <div className="flex h-screen w-screen overflow-hidden">
              {/* Sidebar */}
              <AppSidebar />

              {/* Main content */}
              <main className="flex-1 overflow-y-auto overflow-x-hidden">
                <SidebarTrigger />
                <div className="p-6">{children}</div>
              </main>
            </div>
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  )
}
